markdown: redcarpet
name: Agile City Performance Playbook
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

baseurl: /agilecity

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Jonathan Pichot, Adrian Dahlin, Chris Streich, Maisha Lopa, and Danny Fay
  url: https://github.com/cusp2017

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Who Is This For?
  internal: true
- text: Where To Start
  url: where-to-start/
  internal: true
- text: Data Pipeline
  url: data-pipeline/
  internal: true
  children:
  - text: 1. Find The Data
    url: 1-find-the-data/
    internal: true
  - text: 2. Cleaning and Consolidating
    url: 2-cleaning-and-consolidation/
    internal: true
  - text: 3. Output
    url: 3-output/
    internal: true
- text: Data Quality
  url: data-quality/
  internal: true
- text: Document Your Process
  url: document-your-process/
  internal: true
- text: Public Outreach
  url: public-outreach/
  internal: true
- text: Privacy & Ethics
  url: privacy-and-ethics/
  internal: true
  children:
  - text: The Dangers of Data
    url: the-danger-of-data/
    internal: true
- text: Managing Change
  url: managing-change/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/guides-template

google_analytics_ua: null

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
